#!/usr/bin/env node

require('coffee-script');
var path = require('path');                                                        
var fs   = require('fs');                                                          
var dirname = path.dirname(fs.realpathSync(__filename));
var lib  = path.join(dirname, '../lib');         

require(lib + '/command')(path.join(dirname, '..'));
